### PR TITLE
fix-#257: Implemented show/hide password functionality

### LINKED ISSUE #257: Hide and visible in password to improve UI
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is good to add seen  and unseen feature in sing in page . It give a choice to user to check its password before sign in

### Expected Behavior

_No response_

### Reproduction steps

```bash
1. Go to sign in page
3. Scroll down to password
4. See error there is no hid and visible icon.
```

### Screenshots

DESCRIPTION
Screenshot 2024-05-16 224304

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by rushil-b-patel**
## Summary

Implemented the show/hide password functionality with state & react icons.

## Description

1. Added a new state for passwordvisible and setpasswordvisible function to set the value true/false.
2. Included the state in **type** attribute of input field of password, which toggles the type from text to password according to the state's value.
3. Add new svg files of eye & eye-off in the assets folder.
4. And finally implement a button which toggles the state's value from false to true and vice-versa using **SVG icons**.

## Images

[passwordVisibility.webm](https://github.com/krishnaacharyaa/wanderlust/assets/96254453/21f29192-e777-489a-8378-ada604239c47)
(it supports the mobile responsive also so no need to change any thing :) ) 

## Issue(s) Addressed

Closes #257 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

File: backend/app.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ app.use(cors({
     credentials: true
 }));
 app.use(express.json());
-app.use(express.urlencoded({ extended: true }));
+app.use(express.urlencoded());
```
Comment (krishnaacharyaa) [inline backend/app.js:19]: why this change

File: frontend/src/pages/signin-page.tsx [hunk 2]
```diff
@@ -90,13 +95,20 @@ function signin() {
...
               placeholder="Password"
               className="w-full rounded-lg bg-zinc-100 p-3 font-normal placeholder:text-sm dark:bg-dark-field dark:text-dark-textInField"
             />
+            <button
+              type="button"
+              onClick={() => setPasswordVisible(!passwordVisible)}
+              className="absolute inset-y-0 right-0 flex items-center pr-3 text-sm leading-5"
+            >
+              <img src={passwordVisible ? EyeOffIcon : EyeIcon} alt="Toggle-visibility" className="w-5 h-5" />
+            </button>
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signin-page.tsx:111]: {passwordVisible ? EyeOffIcon : EyeIcon} ideally should be {passwordVisible ? EyeIcon : EyeOffIcon}

File: frontend/src/pages/signin-page.tsx [hunk 3]
```diff
@@ -90,13 +95,20 @@ function signin() {
...
-              type="password"
+              type={passwordVisible ? 'text' : 'password'}
               placeholder="Password"
               className="w-full rounded-lg bg-zinc-100 p-3 font-normal placeholder:text-sm dark:bg-dark-field dark:text-dark-textInField"
             />
+            <button
+              type="button"
+              onClick={() => setPasswordVisible(!passwordVisible)}
+              className="absolute inset-y-0 right-0 flex items-center pr-3 text-sm leading-5"
+            >
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signin-page.tsx:109]: Kindly make sure if this works in the mobile screen as well, can you add the video recorded for the mobile screen as well

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
LGTM, the first commit "revert" doesn't follow the guidelines, but i'll let it slide. Kindly address the review comments

File: backend/app.js (hunk 1 above)
Comment (rushil-b-patel) [reply backend/app.js:19]: this is what I was saying that I commited that payload vala change but I tried to undo that commit through revert but I don't I didn't find my way but managed to undo in this commit. So it will the same the app.js (backend) won't change.

File: frontend/src/pages/signin-page.tsx (hunk 2 above)
Comment (rushil-b-patel) [reply frontend/src/pages/signin-page.tsx:111]: ohh My bad, yes you are correct. Let me change that...

File: frontend/src/pages/signin-page.tsx (hunk 3 above)
Comment (rushil-b-patel) [reply frontend/src/pages/signin-page.tsx:109]: sure @krishnaacharyaa

File: backend/app.js (hunk 1 above)
Comment (krishnaacharyaa) [reply backend/app.js:19]: payload vala change, i didn't get.
But if this is unexpected and want to get back, make a new commit reverting the changes

**Comment by rushil-b-patel** [comment]
goog to go...! @krishnaacharyaa

File: backend/app.js (hunk 1 above)
Comment (rushil-b-patel) [reply backend/app.js:19]: umm what I was saying is that I made a commit changing the _app.use(express.urlencoded());_ to _app.use(express.urlencoded({ extended: true }));_ but I revert the changes while addressing this password vala issue so in this commit it will get back to normal **app.use(express.urlencoded());** which is already there in the main branch, so it won't affect.

Comment (krishnaacharyaa) [reply backend/app.js:19]: Oh okay, you are saying previously you were the one who made this changes is it?

Comment (rushil-b-patel) [reply backend/app.js:19]: yes and now changed it back to normal

Comment (krishnaacharyaa) [reply backend/app.js:19]: Can you please share the PR? @rushil-b-patel 
https://github.com/krishnaacharyaa/wanderlust/pull/292/files
Here i don't see the changes

Comment (rushil-b-patel) [reply backend/app.js:19]: sorry I did't get

Comment (krishnaacharyaa) [reply backend/app.js:19]: Just change it back to this so that I can merge
`app.use(express.urlencoded({ extended: true }));`

Comment (rushil-b-patel) [reply backend/app.js:19]: were you talking about this PR ?
image

Comment (krishnaacharyaa) [reply backend/app.js:19]: > umm what I was saying is that I made a commit changing the app.use(express.urlencoded()); to app.use(express.urlencoded({ extended: true }));

This never happened in the main branch, it might be in the private branch

Comment (krishnaacharyaa) [reply backend/app.js:19]: > Just change it back to this so that I can merge `app.use(express.urlencoded({ extended: true }));`

Just do this,

Comment (rushil-b-patel) [reply backend/app.js:19]: yes it was in private repo.
You want to change from **app.use(express.urlencoded());** to this **app.use(express.urlencoded({ extended: true }));**..? @krishnaacharyaa

Comment (rushil-b-patel) [reply backend/app.js:19]: any update...? @krishnaacharyaa

Comment (krishnaacharyaa) [reply backend/app.js:19]: I have updated long time ago with the emoji

**Comment by rushil-b-patel** [comment]
Good to go.. @krishnaacharyaa ...!

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, thanks
