### PR TITLE
fix-#6: integration test completed for signin component 

### LINKED ISSUE #6: Adding integration tests in frontend
Presently we do not have any test cases written in the application which ensures security, as the project grows in the size there are high chances that the application can break. So adding relevant test cases would be very handy.
Mostly likes framework like jest can be used to achieve this, if any other framework which is better than this, we can discuss and proceed.

### PR DESCRIPTION
**Pull request by Aswin2255**
The integration test completed for the sign-in component fixed the unit case failure due to the new changes introduced 

## Summary

An integration test is performed on the sign-in component using the real backend API 

## Description
To perform the integration test we need to run the backend, also we need to have a test user in the database with the test credentials

## Images

image

## Issue(s) Address

#6 

- Closes #6 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

File: backend/app.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ const app = express();
 app.use(
   cors({
     // added origin
-    origin: FRONTEND_URL,
+    origin: [FRONTEND_URL, 'http://localhost:3000'],
     credentials: true,
```
Comment (krishnaacharyaa) [inline backend/app.js:17]: What is this change?

File: frontend/src/__tests__/mocks/handeler-mock.ts [hunk 2]
```diff
@@ -2,7 +2,7 @@
 import { http, HttpResponse } from 'msw';
 
 export const handlers = [
-  http.post('http://localhost:5000/api/auth/email-password/signup', () => {
+  http.post('http://localhost:8080/api/auth/email-password/signup', () => {
     return new HttpResponse(null, {
```
Comment (krishnaacharyaa) [inline frontend/src/__tests__/mocks/handeler-mock.ts:6]: No hard coding please

File: frontend/src/__tests__/unit-test/signup/signup.test.tsx [hunk 3]
```diff
@@ -7,10 +7,30 @@ import {
...
   INVALID_PWD_ERRORMESSAGE,
-  INVALID_USERNAME_ERRORMESSAGE,
+  NAME_EMPTY_ERRORMESSAGE,
   PASSWORD_EMPTY_ERRORMESSAGE,
   USERNAME_EMPTY_ERRORMESSAGE,
 } from '@/constants/images';
+import { toast } from 'react-toastify';
+
+interface sucessdata {
+  status: number;
```
Comment (krishnaacharyaa) [inline frontend/src/__tests__/unit-test/signup/signup.test.tsx:17]: I see this used multiple places, can we have a seperate types folder? and make it reusable

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Thank you Ashwin, But please prepare tests for many other scenarios, ideally tests should contain all the scenarios it might go to crazy number, 
Can you kindly enhance this to have decent amount of test cases which covers all the scenarios?

**Comment by krishnaacharyaa** [comment]
@Aswin2255

File: backend/app.js (hunk 1 above)
Comment (Aswin2255) [reply backend/app.js:17]: since we are doing an integration test with the real API. The jsdom is our frontend and it's default URL is localhost:3000,  so if we doesn't include it we will get an cors error during integration test..

**Review by krishnaacharyaa — APPROVED** [review]
