### PR TITLE
fix: Make the add page responsive

### LINKED ISSUE #15: Make the add page responsive
Presently the categories are disoriented and the font size is too big and horizontal padding is too big and we might have to span the button full width for best practice in the mobile device
image

We have to make it responsive for devices 
1. Greater than desktop
2. Desktop devices
3. Tablet devices
4. mobile devices

### PR DESCRIPTION
**Pull request by SankalpHaritash21**
## Summary
Adding Responsive Layout to add-blog page

## Description
add-blog page is not responsive. Now, adding responsiveness to add-blog page according to Laptop, Tablet, Mobile.

## Images
Mobile:
mobile1

Tablet:
Tablet

Laptop:
Laptop

## Issue(s) Addressed
- Closed #15  

## Review Checklist
Please make sure to go through this checklist before submitting your review.

- [X] Make sure the PR title is of format **`tag: Issue Title`**
   - tag should be one of `fix`,`feat`, `docs`, `chore`, `refactor`
   - Ex: `feat: Added responsive design for the home page`
- [X] Ensure the code follows our coding standards and guidelines
   - Ex:  naming conventions should be of form `file-name.ts` not `fileName.ts`
- [X] Ensure that you have staged only the required commits and raised the PR and not included all the files which would be otherwise required for local setup
- [X] Check if the PR is rebased to the latest main/development branch.
- [X] Make sure there are no unnecessary files or debugging artifacts in the PR.

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Hi @SankalpHaritash21 , i still dont think header and hint texts are 22px and 16px respectively, please check the same.

File: frontend/src/pages/add-blog.tsx [hunk 1]
```diff
@@ -129,17 +129,8 @@ function AddBlog() {
           />
         </div>
 
-        <div className="mb-4">
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:132]: Why have you removed description from here ?

File: frontend/src/pages/add-blog.tsx [hunk 2]
```diff
@@ -157,20 +148,32 @@ function AddBlog() {
             ))}
           </div>
         </div>
+        <div className="mt-4 mb-4 ">
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:151]: Revert the order to description and then categories as before

File: frontend/src/pages/add-blog.tsx [hunk 3]
```diff
@@ -157,20 +148,32 @@ function AddBlog() {
...
             />
-            <span className="text-gray-800 text-base font-medium">Featured Post</span>
           </label>
         </div>
 
-        <button type="submit" className="bg-black text-white p-2 rounded-lg hover:bg-gray-800">
+        <button
+          type="submit"
+          className="bg-black text-white text-[16px] md:text-lg lg:text-xl p-2 rounded-lg hover:bg-gray-800 w-full md:w-fit"
+        >
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:176]: try to use equivalent tailwind-css class than hardcoding 16px

File: frontend/src/pages/add-blog.tsx (hunk 1 above)
Comment (SankalpHaritash21) [reply frontend/src/pages/add-blog.tsx:132]: sir I removed description from here because it is givn in your figma design

figma

File: frontend/src/pages/add-blog.tsx (hunk 2 above)
Comment (SankalpHaritash21) [reply frontend/src/pages/add-blog.tsx:151]: Should I follow your figma design or I revert it?

File: frontend/src/pages/add-blog.tsx (hunk 3 above)
Comment (SankalpHaritash21) [reply frontend/src/pages/add-blog.tsx:176]: Ok sir I will make it as text-sm or text-base

File: frontend/src/pages/add-blog.tsx (hunk 1 above)
Comment (krishnaacharyaa) [reply frontend/src/pages/add-blog.tsx:132]: Ooh my bad, I'll change that in the figma file, lets keep it original to the code , description and then categories.

File: frontend/src/pages/add-blog.tsx (hunk 2 above)
Comment (krishnaacharyaa) [reply frontend/src/pages/add-blog.tsx:151]: Please revert it , i'll change it in the figma file by end of the day, just try focusing on the font size for now nothing else.

File: frontend/src/pages/add-blog.tsx (hunk 3 above)
Comment (krishnaacharyaa) [reply frontend/src/pages/add-blog.tsx:176]: Sure anything that is close to 16px, please refer the documentation for this

File: frontend/src/pages/add-blog.tsx (hunk 1 above)
Comment (SankalpHaritash21) [reply frontend/src/pages/add-blog.tsx:132]: sir it look great to first keep categories first User can write description by keeping category in mind

File: frontend/src/pages/add-blog.tsx (hunk 2 above)
Comment (SankalpHaritash21) [reply frontend/src/pages/add-blog.tsx:151]: ok sir I will revert it in code

**Comment by SankalpHaritash21** [comment]
value

I updated text-base which is accurately 16px. Now values are not hard coded

**Review by krishnaacharyaa — APPROVED** [review]
Thank you for the changes, looks good to me, I'll approve the PR :)
