### PR TITLE
theme-toggle-button

### LINKED ISSUE #36: Add a toggle switch to switch between light and dark mode
We are presently working on default theme #16, but we would be also needing to give option to the user to have manual switch to toggle which influence the theme of the application

### LINKED ISSUE #97: [BUG] In All Post section Card
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the card which has large description is clicked, some part of the description is in viewport initially not the top of the post, that is Image and the start of description is not in viewport initially when the card is clicked.
Current behaviour :

Screenshot 2024-01-05 at 11 18 22 PM

### Expected Behavior

When is card with large description is clicked , the top of post ( that is image and the start of the description )should be in viewport initially.
Expected behaviour :

Screenshot 2024-01-05 at 11 18 36 PM

### Reproduction URL

https://github.com/Raghunandan-29

### Reproduction steps

```bash
1. Go to 'All Post section'
2. Click on 'Capturing the Cityscape at Night: A Mesmerising Experience by Alice Smith' card
3. Checkout the content which in viewport initially.
4. Initially the top of this post page should be in viewport rather than the part of description.
5. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

Chrome

### OS

Mac

### PR DESCRIPTION
**Pull request by Raghunandan-29**
## Summary
This PR  resolves issue #36 and issue #97
## Description
This PR adds Theme-toggle-button and also scroll to top for posts which has the larger description 
## Images
Theme-toggle button is responsive :
this is for mobile screens
Screenshot 2024-01-11 at 12 56 37 AM
 
this is for tablet and desktop screens

Screenshot 2024-01-11 at 5 05 51 PM

## Issue(s) Addressed

Closes #36
Closes #97
## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by krishnaacharyaa** [comment]
Hi @Raghunandan-29 , thank you for the PR, LGTM. Just couple of suggestions.
Can we aim the css to be like this
IMG_20240102_073026
And kindly follow all the Community guidelines and PR template page as discussed in the discord to make it eligible candidate for merging...

**Comment by Raghunandan-29** [comment]
Sure, I will change the CSS and also follow the Community guidelines

**Comment by krishnaacharyaa** [comment]
Can you kindly push the changes @Raghunandan-29 which is posted in the discord

File: frontend/src/App.tsx [hunk 1]
```diff
@@ -2,12 +2,14 @@ import { BrowserRouter, Routes, Route } from 'react-router-dom';
...
 import DetailsPage from '@/pages/details-page';
+import ScrollToTop from "@/components/skeletons/ScrollTop";
 function App() {
   return (
     <BrowserRouter>
+    <ScrollToTop />
       <Routes>
         <Route path="/">
-          <Route index element={<HomePage />} />
+          <Route index element={<HomePage />}/>
```
Comment (krishnaacharyaa) [inline frontend/src/App.tsx:12]: Can you kindly run `npm run format` in the frontend directory, because it helps in readability

File: frontend/src/components/skeletons/ScrollTop.tsx
Comment (krishnaacharyaa) [inline frontend/src/components/skeletons/ScrollTop.tsx:1]: kindly rename to `scroll-to-top.tsx`, as mentioned in the 4th point of [contributing guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/cfeab89861b81827361a115adb339f628e24abe6/.github/CONTRIBUTING.md#guidelines-for-contributions).
And why is it inside the skeletons directory?

File: frontend/src/components/theme-toggle.tsx
Comment (krishnaacharyaa) [inline frontend/src/components/theme-toggle.tsx:1]: I feel `theme-toggle-button` would be a better naming for this

File: frontend/src/components/theme-toggle.tsx [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+      }
+    }, [isDarkTheme]);
+  return (
+    <div>
+      <label htmlFor="theme" className="theme cursor-pointer">  
+        <span className="theme__toggle-wrap cursor-pointer">  
+          <input id="theme" className="theme__toggle cursor-pointer" readOnly type="checkbox" role="switch" name="theme" value="dark" onClick={toggleTheme} checked={isDarkTheme === true} />  
+          {/* <span className="theme__fill"></span>   */}
+          <span className="theme__icon">  
+            <span className="theme__icon-part"></span>
```
Comment (krishnaacharyaa) [inline frontend/src/components/theme-toggle.tsx:38]: Can we kindly optimize this, doesn't look nice... code wise, can we work on this and see if we can use just tailwind-css for this and not use plain-css

File: frontend/src/components/theme-toggle.tsx [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+        // Save the user's theme preference to local storage
+        localStorage.setItem('theme', isDarkTheme ? 'dark' : 'light');
+      }
+    }, [isDarkTheme]);
+  return (
+    <div>
+      <label htmlFor="theme" className="theme cursor-pointer">  
+        <span className="theme__toggle-wrap cursor-pointer">  
+          <input id="theme" className="theme__toggle cursor-pointer" readOnly type="checkbox" role="switch" name="theme" value="dark" onClick={toggleTheme} checked={isDarkTheme === true} />  
+          {/* <span className="theme__fill"></span>   */}
```
Comment (krishnaacharyaa) [inline frontend/src/components/theme-toggle.tsx:36]: Why are we having this commented line?

File: frontend/src/index.css
Comment (krishnaacharyaa) [inline frontend/src/index.css:1]: `index.css`, lets try to not use this, and replace it with tailwind-css, if it is not possible at all, as a last resort lets go with this, then we might have to rename this specific to the toggle-button so it would be more readable.

File: frontend/src/pages/add-blog.tsx [hunk 4]
```diff
@@ -111,24 +111,31 @@ function AddBlog() {
...
-      mediaQuery.removeListener(handleThemeChange);
-    };
-  }, []);
+  //   mediaQuery.addListener(handleThemeChange);
+
+  //   return () => {
+  //     mediaQuery.removeListener(handleThemeChange);
+  //   };
+  // }, []);
+  // if(storedTheme === 'dark') setIsDarkMode(true);
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:139]: I see there are lots of commented code, kindly delete them, and keep only the required comments, tbh comments are actually not required, in a first look seems like you have directly copy pasted from chat-gpt, i may be wrong, but for the first honest opinion it looks that way :)

File: frontend/src/pages/home-page.tsx [hunk 5]
```diff
@@ -30,15 +32,28 @@ function HomePage() {
...
             >
               Create post
             </button>
+            <button
+              className="md:hidden px-2 py-2 hover:bg-slate-500/25"
+              onClick={() => {
+                navigate('/add-blog');
+              }}
+            >
+             <svg className="h-8 w-8 text-white"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  strokeWidth="2"  strokeLinecap="round"  strokeLinejoin="round">  <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />  <line x1="12" y1="8" x2="12" y2="16" />  <line x1="8" y1="12" x2="16" y2="12" /></svg>
```
Comment (krishnaacharyaa) [inline frontend/src/pages/home-page.tsx:54]: Kindly take this out as a svg component and place it where all the svgs are placed and then pull it as a component

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Thank you @Raghunandan-29 for this amazing much needed PR, end functionality wise looks cool, but we also aim for code quality, which is presently not satisfying, kindly address the comments, and please follow the comunity guidelines, 
1, 2,3, 4, 5was not followed, is what I observed, 
Looking forward for the upcoming commits :)

File: frontend/src/components/skeletons/ScrollTop.tsx
Comment (Raghunandan-29) [reply frontend/src/components/skeletons/ScrollTop.tsx:1]: could you please suggest me that in which directory scroll-to-top.tsx should present

Comment (krishnaacharyaa) [reply frontend/src/components/skeletons/ScrollTop.tsx:1]: For now you can have it in the components folder

**Comment by krishnaacharyaa** [comment]
@Raghunandan-29 updates please

**Comment by Raghunandan-29** [comment]
Sorry krishna, I accidentally changes the path of skeleton.tsx, I will fix this

**Review by krishnaacharyaa — COMMENTED** [review]
Hey @Raghunandan-29, thank you for the quick update and sincere considerations of the comments and working on it. 
Sorry but still the community guidelines of PR title and commit regex is not followed, hopefully you'll pick that up in the next one, apart from that no complaints, the quality is improved 200% from the previous one and this is the very quality we are aiming for.
Thank you @Raghunandan-29 

Just a small observation here when i saw the deployment, when you are in the dark mode and come back to home page from details or add page, you see the default is sun and then it switches to the dark, for a millisecond that happens, can you look into it? 
It might be a little challenging, you might have to play with react hooks in a better way, but would be a great learning, can you pick this one part in this PR then we can close, or if you want to take it in the another PR, we'll take it, I am totally okay with that :)

**Comment by Raghunandan-29** [comment]
Thanks Krishna! and for that bug I would like to work with new PR so, I will raise new issue for this and work on it. Hope it is okay with you.

**Comment by krishnaacharyaa** [comment]
Please share the created link of the issue here, so that we can merge this PR

**Comment by Raghunandan-29** [comment]
Issue link  https://github.com/krishnaacharyaa/wanderlust/issues/98#issue-2080611452

**Review by krishnaacharyaa — APPROVED** [review]
Thank you @Raghunandan-29, LGTM merging now
