### PR TITLE
fix-#258: Now icons are visible in mobile screen instead of both button + icons ( login, logout and creat post) and aligned header too.

### LINKED ISSUE #258: [BUG] Login, Logout and Create post icons + buttons are visible in small screen and alignment is broken too.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, application's main icons such as login ,  logout and create post icons + buttons are both visible in mobile screens which is not a good user experience. And header + these icons alignments are not correct with the application overall alignment.

Screenshot 2024-05-17 020409

Screenshot 2024-05-17 020438

### Expected Behavior

Application's main icons should be visible in mobile screens instead of buttons + icons both. And there should be proper alignment of these header icons with application.

Screenshot 2024-05-17 020551

Screenshot 2024-05-17 020611

### Reproduction steps

```bash
1. Go to 'https://wanderlust-beta.vercel.app/'
2. Minimize the screen ( inspect and click on toggle device toolbar )
4. See error
```

### PR DESCRIPTION
**Pull request by 0xmohitsen**
## Summary

This PR aims to display icons in mobile screen + resolves header alignment.

## Description

This PR is basically makes the buttons hidden in mobile screen so that icons can be visible. And gives some styling to make header aligned with overall application.

## Images

Current behavior as expected :-
Screenshot 2024-05-17 020551

Screenshot 2024-05-17 020611

## Issue(s) Addressed

closes #258 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

File: frontend/src/layouts/header-layout.tsx [hunk 1]
```diff
@@ -53,30 +53,30 @@ function header() {
   return (
     <div className="relative -mt-2 h-[460px] bg-[url('./assets/wanderlustbg.webp')] bg-cover bg-fixed bg-center">
       <div className="absolute inset-0 bg-black opacity-50"></div>
-      <div className="absolute inset-0 flex flex-col px-4 py-8 text-slate-50 sm:px-16">
+      <div className="absolute inset-0 flex flex-col px-4 py-8 text-slate-50 sm:px-8 lg:px-16">
         <div className="flex w-full justify-between">
```
Comment (krishnaacharyaa) [inline frontend/src/layouts/header-layout.tsx:57]: please remove lg: and it should ideally be px-8 and sm:px-16, figure out why, its interesting

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]

File: frontend/src/layouts/header-layout.tsx (hunk 1 above)
Comment (0xmohitsen) [reply frontend/src/layouts/header-layout.tsx:57]: I made changes to make it aligned with the blog feed which has css on line no. 27.

Comment (0xmohitsen) [reply frontend/src/layouts/header-layout.tsx:57]: > please remove lg: and it should ideally be px-8 and sm:px-16, figure out why, its interesting

If i remove lg and keep the changes to px-8 and sm:px-16 alignment doesn't look good.

I'll remove it if it is not needed.

Comment (0xmohitsen) [reply frontend/src/layouts/header-layout.tsx:57]: > please remove lg: and it should ideally be px-8 and sm:px-16, figure out why, its interesting

Sure.

**Comment by krishnaacharyaa** [comment]
Done?

**Comment by 0xmohitsen** [comment]
> Done?

Going to complete it now. 

was busy with other works.

**Comment by 0xmohitsen** [comment]
> Done?

Made the suggested changes.

**Review by krishnaacharyaa — APPROVED** [review]
LGTM
