### PR TITLE
fix-#77: changed the traditional form to react hook form

### LINKED ISSUE #77: Refactor Form vailidation using the react-hook-form and zod
### Description

1. Getting values in and out of form state
2. Validation and error messages
3. Handling form submission

we can use formik or useform library for the validation

**why Formik ?**

Formik keeps track of your form's state and then exposes it plus a few reusable methods and event handlers (handleChange, handleBlur, and handleSubmit) to your form via props

Formik and useForm are the mostly used library and it can handle a lot of things **very good for learning prospective also**

### Current Behavior

1. There are **no validation** of the **title** of the post like there should be **minimum 3 char** for the title.
2.  There are no validation for the **author name** which maybe we can handle with the **authentication** but still it should have minimum '**3 character in a author name** '
3. Required error is not shown **before clicking on the submit Button**

### Proposed Enhancement

The validation help us to post the right type of data in the blog post we need also can reduce the chances of wrong and trash data by adding some validation like if we want email then this should have some patter text@domain-name.topleveldomain like in,co,com etc  

### Attachment
image

### PR DESCRIPTION
**Pull request by Ameerjafar**
## Summary

I have converted the react traditional form to the react hook form.

## Description
I have done the react hook form to reduce the lot of re-renders at the same time users can easily identify the error while they are trying to add the blog in the application and for the  form validation i have used zod library.

## Images

https://github.com/krishnaacharyaa/wanderlust/assets/105500361/16fc38ec-686c-40dd-8ed6-64ed2595ff5d

## Issue(s) Addressed

_Enter the issue number of the bug(s) that this PR fixes_

- Template should be strictly **Closes <#77>**
- Example: Closes #77 

## Prerequisites

- [ yes ] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

**Comment by Ameerjafar** [comment]
@krishnaacharyaa can you kindly review this one sir.

**Comment by krishnaacharyaa** [comment]
@Ameerjafar can you kindly add the video

**Comment by krishnaacharyaa** [comment]
image

Kindly update the validations to these and messages also,

And once go through https://github.com/krishnaacharyaa/wanderlust/pull/83/files, might be of help

**Comment by krishnaacharyaa** [comment]
@Ameerjafar in the video, when no categories is selected it says "max three categories" and when you click 2 categories it won't go...

Shoudln't that error come when you click more than 3 categories? 
And when you haven't clicked it should say please select a category something and when you click a category the error message should go

File: frontend/src/lib/types.ts [hunk 1]
```diff
@@ -28,6 +28,38 @@ export const signUpSchema = z
     message: 'Confirm Password do not match',
     path: ['confirmPassword'],
   });
+const isValidImageLink = (value: string) => {
+  const imageLinkRegex = /\.(jpg|jpeg|png|webp)$/i;
```
Comment (krishnaacharyaa) [inline frontend/src/lib/types.ts:32]: Do we actually need a function? Can't we inline using the .validate option which zod provides directly

File: frontend/src/lib/types.ts [hunk 2]
```diff
@@ -28,6 +28,38 @@ export const signUpSchema = z
...
+    message: 'Hmm... Image link should end with .jpg, .jpeg, .webp, or .png.',
+  }),
+  categories: z
+    .array(z.string())
+    .min(1, {
+      message: 'Easy there! Select at least one category.',
+    })
+    .max(3, {
+      message: 'Easy there! Not more than 3 categories.',
+    }),
```
Comment (krishnaacharyaa) [inline frontend/src/lib/types.ts:61]: 😂

File: frontend/src/pages/add-blog.tsx [hunk 3]
```diff
@@ -236,35 +200,48 @@ function AddBlog() {
...
+              <span
+                {...register('categories')}
+                className="text-xs tracking-wide text-dark-tertiary"
+              >
                 &nbsp;(max 3 categories)&nbsp;
               </span>
               <Asterisk />
+              <br></br>
+              {errors.categories && (
+                <span className="text-sm text-red-500">{`${errors.categories.message}`}</span>
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:243]: The error section of the categories should go below the categories selection ig, because in every other thing error is below, only in the cateogry it is above the actual category section

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Hi @Ameerjafar , thank you
When 1 category I didn't see the error message vanishing in the video.

And please also select 3 categories and see if lets you select 4th one

File: frontend/src/pages/add-blog.tsx (hunk 3 above)
Comment (Ameerjafar) [reply frontend/src/pages/add-blog.tsx:243]: ok sir

File: frontend/src/lib/types.ts (hunk 1 above)
Comment (Ameerjafar) [reply frontend/src/lib/types.ts:32]: .validate is when we are giving some url to test whether that url meets the defined schema or not @krishnaacharyaa

Comment (krishnaacharyaa) [reply frontend/src/lib/types.ts:32]: @Ameerjafar okay if we can't inline then fine, but i guess inline/arrow function can be written

File: frontend/src/pages/add-blog.tsx (hunk 3 above)
Comment (Ameerjafar) [reply frontend/src/pages/add-blog.tsx:243]: Done sir

**Comment by Ameerjafar** [comment]
> Hi @Ameerjafar , thank you When 1 category I didn't see the error message vanishing in the video.
> 
> And please also select 3 categories and see if lets you select 4th one

**Review by krishnaacharyaa — APPROVED** [review]
Thanks for the efforts as always @Ameerjafar
