### PR TITLE
fix-#432: Bug Fixed

### LINKED ISSUE #432: [BUG] header should be displayed properly in signup and login page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Reproduction steps

```bash
Header should be showing properly in mobile
```

### Screenshots

DESCRIPTION
Screenshot_20240625_233930

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by kapilG0**
## Summary

Fixed header for signup and login page in mobile
## Description

Header fixed for signup and login page

## Images

image
image

## Issue(s) Addressed

   Closes #432 

## Prerequisites

- [x] Have you followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)?

### CODE REVIEW

File: frontend/src/pages/signin-page.tsx [hunk 1]
```diff
@@ -73,7 +73,7 @@ function signin() {
     <div className="flex-grow cursor-default bg-white py-4 dark:bg-dark-card">
       <div className="m-4 mb-4 flex justify-center">
         <div className="flex w-full items-center justify-center">
-          <h2 className="w-3/4 pl-48 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
+          <h2 className="w-3/4 pl-2 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
             Sign in to WanderLust
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signin-page.tsx:77]: This will make the desktop app look bad, pl-2 should be only for the mobile devices

File: frontend/src/pages/signup-page.tsx [hunk 2]
```diff
@@ -68,7 +68,7 @@ function Signup() {
     <div className="flex-grow cursor-default bg-white py-4 dark:bg-dark-card">
       <div className="m-4 mb-4 flex justify-center">
         <div className="flex w-full items-center justify-center">
-          <h2 className="w-3/4 pl-48 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
+          <h2 className="w-3/4 pl-2 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
             Sign up to WanderLust
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signup-page.tsx:72]: Same comment

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Thank you @kapilG0 , Kindly address the review comments and add snapshots of the desktop view even to cross check.

File: frontend/src/pages/signin-page.tsx (hunk 1 above)
Comment (kapilG0) [reply frontend/src/pages/signin-page.tsx:77]: Hello @krishnaacharyaa i am attaching image for sign up page 
for mobile
image
for ipad
image
for desktop

Comment (kapilG0) [reply frontend/src/pages/signin-page.tsx:77]: Hello @krishnaacharyaa please check i have pushed new changes in same commit

**Comment by krishnaacharyaa** [comment]
@kapilG0 take some time, and go through https://tailwindcss.com/docs/responsive-design , and get back, 
The solution shouldn't be more than 6 to 8 characters meaning it is that minor change, you don't have to create new custom classes and stuff. And forget about the tablet screen, 

The task is not to the existing code base of desktop, only in the mobile it needs to be fixed, figure it out

**Comment by kapilG0** [comment]
> @kapilG0 take some time, and go through https://tailwindcss.com/docs/responsive-design , and get back, The solution shouldn't be more than 6 to 8 characters meaning it is that minor change, you don't have to create new custom classes and stuff. And forget about the tablet screen,
> 
> The task is not to the existing code base of desktop, only in the mobile it needs to be fixed, figure it out

Hello @krishnaacharyaa based on above documentation i changed code .please check below images if it is fine then i will raise pr.
for mobile 
image
for ipad
image
for desktop
image

**Comment by krishnaacharyaa** [comment]
> Hello @krishnaacharyaa based on above documentation i changed code
Kindly push it, so that I can tell if you are on the right track

File: frontend/src/pages/signin-page.tsx (hunk 1 above)
Comment (kapilG0) [reply frontend/src/pages/signin-page.tsx:76]: Hello @krishnaacharyaa i have pushed please check

**Comment by kapilG0** [comment]
> > Hello @krishnaacharyaa based on above documentation i changed code
> 
> Kindly push it, so that I can tell if you are on the right track

i have pushed please check

File: frontend/src/pages/signup-page.tsx [hunk 3]
```diff
@@ -68,7 +67,7 @@ function Signup() {
     <div className="flex-grow cursor-default bg-white py-4 dark:bg-dark-card">
       <div className="m-4 mb-4 flex justify-center">
         <div className="flex w-full items-center justify-center">
-          <h2 className="w-3/4 pl-48 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
+          <h2 className="text-center text-lg font-bold text-black dark:text-dark-primary sm:w-2/4 sm:pl-2 sm:text-xl lg:w-3/4 lg:pl-48">
             Sign up to WanderLust
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signup-page.tsx:71]: you mean to say `w-2/4 text-xl md:w-3/4 md:pl-48`? 

You are almost there, figure out why i said the above instead of `sm:w-2/4 sm:pl-2 sm:text-xl lg:w-3/4 lg:pl-48`

ps: We are focusing on mobile and devices with greater than mobile width screen . i.e md: and default should only be used, you can see the repo, no where we are using the `lg:`, you have solution here, please change it and try to understand why this change i suggested :)

File: frontend/src/pages/signin-page.tsx [hunk 4]
```diff
@@ -73,7 +72,7 @@ function signin() {
     <div className="flex-grow cursor-default bg-white py-4 dark:bg-dark-card">
       <div className="m-4 mb-4 flex justify-center">
         <div className="flex w-full items-center justify-center">
-          <h2 className="w-3/4 pl-48 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
+          <h2 className="text-center text-lg font-bold text-black dark:text-dark-primary sm:w-2/4 sm:pl-2 sm:text-xl lg:w-3/4 lg:pl-48">
             Sign in to WanderLust
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signin-page.tsx:76]: same comment

File: frontend/src/pages/signup-page.tsx (hunk 3 above)
Comment (kapilG0) [reply frontend/src/pages/signup-page.tsx:71]: > you mean to say `w-2/4 text-xl md:w-3/4 md:pl-48`?
> 
> You are almost there, figure out why i said the above instead of `sm:w-2/4 sm:pl-2 sm:text-xl lg:w-3/4 lg:pl-48`
> 
> ps: We are focusing on mobile and devices with greater than mobile width screen . i.e md: and default should only be used, you can see the repo, no where we are using the `lg:`, you have solution here, please change it and try to understand why this change i suggested :)

ok now i understood by default it will be desktop and for mobile and screen small than desktop we should add sm,md for that right ?

Comment (krishnaacharyaa) [reply frontend/src/pages/signup-page.tsx:71]: > ok now i understood by default it will be desktop and for mobile and screen small than desktop we should add sm,md for that right ?

Default is for mobile @kapilG0 in tailwind-css, in bootstrap it was what you are saying

Comment (kapilG0) [reply frontend/src/pages/signup-page.tsx:71]: > > ok now i understood by default it will be desktop and for mobile and screen small than desktop we should add sm,md for that right ?
> 
> Default is for mobile @kapilG0 in tailwind-css, in bootstrap it was what you are saying

oh ok. thank you for clearing and helping me a lot in that . i have never use tailwind i will check some resource for that.

File: frontend/src/pages/signin-page.tsx [hunk 5]
```diff
@@ -73,7 +72,7 @@ function signin() {
     <div className="flex-grow cursor-default bg-white py-4 dark:bg-dark-card">
       <div className="m-4 mb-4 flex justify-center">
         <div className="flex w-full items-center justify-center">
-          <h2 className="w-3/4 pl-48 text-center text-lg font-bold text-black dark:text-dark-primary sm:text-xl">
+          <h2 className="text-center text-lg font-bold text-black dark:text-dark-primary sm:w-2/4 sm:pl-2 sm:text-xl md:w-3/4 md:pl-48">
             Sign in to WanderLust
```
Comment (krishnaacharyaa) [inline frontend/src/pages/signin-page.tsx:76]: As discussed you would have to remove sm: because mobile screen would be less with than sm: and we need this for mobile screen right? which is default. so why do we need to add sm: correct?

File: frontend/src/pages/signup-page.tsx (hunk 3 above)
Comment (krishnaacharyaa) [reply frontend/src/pages/signup-page.tsx:71]: No problem @kapilG0 , the hunger for learning, motivated me to help you :)

Comment (kapilG0) [reply frontend/src/pages/signup-page.tsx:71]: > No problem @kapilG0 , the hunger for learning, motivated me to help you :)

thanks @krishnaacharyaa

File: frontend/src/pages/signin-page.tsx (hunk 5 above)
Comment (kapilG0) [reply frontend/src/pages/signin-page.tsx:76]: > As discussed you would have to remove sm: because mobile screen would be less with than sm: and we need this for mobile screen right? which is default. so why do we need to add sm: correct?

yup understood @krishnaacharyaa

**Review by krishnaacharyaa — APPROVED** [review]
Thank you LGTM
