### PR TITLE
BUGFIX-#165: Categories Sidebar UI issue

### LINKED ISSUE #165: [BUG] Categories Sidebar UI issue While Theme changes, Alignment changes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### BUG- on left sidebar inside <sup> Categories Container </sup> there is a box showing, while change on Theme ###

- On Repetitive switch of Theme There can be seen under the "Categories Box", there is a box over "Tags".

### Expected Behavior

_No response_

### Reproduction steps

```bash
1. Go to 'Home Page'
2. Switch to 'Theme Dark to Light Reputative'
3. See a box over the Tags 
4. also affecting design of website
```

### Screenshots

LightMode
DarkMode

### Logs

_No response_

### Browsers

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by amit429**
BUGFIX#165 : The UI box on the tags in dark theme is removed and the UI now aligns well with the rest and there is no alignment change while changing from light to dark.

## Summary
The issue was related to the UI miss alignment of the tags under category due to the addition of an box in the dark theme. The purpose of this pr is to remove the styling css of tags section in the dark theme to make it aligned with the light themed UI.

## Description
I first identified the location of the styling and then removed the dark theme clause from the inline style of tailwind css to remove the dark box in the UI

## Issues Addressed
1) Earlier n left sidebar inside Categories Container there is a box showing, while change on Theme On Repetitive switch of Theme There can be seen under the "Categories Box", there is a box over "Tags" which was causing a UI Error.
2) This issue was solved by removing the box with bg-dark from the tags section to make the toggle more user friendly as seen in the before and after images below.
Closes #165

## Images
Before 
image

After
image

### CODE REVIEW

File: frontend/src/components/blog-feed.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ export default function BlogFeed() {
             <h2 className="mb-2 cursor-text text-xl font-semibold dark:text-dark-primary">
               Categories
             </h2>
-            <div className="flex flex-wrap gap-3 dark:rounded-lg dark:bg-dark-card dark:p-3">
+            <div className="flex flex-wrap gap-3">
               {categories.map((category) => (
```
Comment (krishnaacharyaa) [inline frontend/src/components/blog-feed.tsx:76]: You have removed bg and rounded corners in darkmode?

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Hi @amit429 Thank you for the PR,
Kindly address the comment

And please follow proper commit guidelines in the next commit

File: frontend/src/components/blog-feed.tsx (hunk 1 above)
Comment (amit429) [reply frontend/src/components/blog-feed.tsx:76]: Yes , the issued raised highlighted the extra box on the tags under category section which caused a little miss alignment while toggling to dark mode so that box was removed so that the dark mode gets aligned with light mode

Comment (krishnaacharyaa) [reply frontend/src/components/blog-feed.tsx:76]: @amit429 why did you have to remove dark:rounded-lg and dark:bg-dark ? the `dark:p-3` was the only guy giving problem, now try the dark mode this category card will never get to dark mode, because of your changes, 
Please test the changes before pushing, and if said politely take some time , understand what I am trying to convey and then get back. Randomly please don't reply back. It consumes lot of my time.

Comment (amit429) [reply frontend/src/components/blog-feed.tsx:76]: hey i am sorry for not getting your point earlier. In the issue number #165 the guy mentioned : BUG- on left sidebar inside Categories Container there is a box showing, while change on Theme On Repetitive switch of Theme There can be seen under the "Categories Box", there is a box over "Tags".

I have comprehended it as it was the issue of the box getting created over the tags in dark mode which needed to be removed , so i had to remove the the background dark from the tags section under categories heading , i am confused on how the issue is just related to the dark:p-3

I have also attached the before after screenshots to show the difference , the issue suggested a bug regarding the dark box getting created over the tags. I have tested the code on local and attached the screenshot 

if i have comprehended it wrongly then please do let me know , i would like to revise the changes

Comment (krishnaacharyaa) [reply frontend/src/components/blog-feed.tsx:76]: You are absolutely right @amit429, sorry for the rude behaviour and words. I was too focused on the alignment changes part, so thought p-4 is causing the problem, has forgotten this is the child of a container in which the dark theme background is already handled.

Thank you for the fix, Kindly make the changes in the PR description to have "Issues addressed section" and we are good to close.

Sincere apologies again for overlooking this. And thanks for your patience, much appreciated

Comment (amit429) [reply frontend/src/components/blog-feed.tsx:76]: @krishnaacharyaa PR description have been updated and issues addressed section is added with reference to the screen shot. I would like to request you to please merge the pr.

**Comment by krishnaacharyaa** [comment]
I meant 
image

Anyways will do it myself, kindly follow from next time

**Review by krishnaacharyaa — APPROVED** [review]
LGTM, thank you for the PR
