### PR TITLE
enhance: #49 Add button inside image url input to generate random images 

### LINKED ISSUE #49: [ENHANCEMENT] Add button inside image url input to generate random images
### Description

Presently, people who want to test are not patient enough to make efforts to find a valid image from the website and then upload, so they normally end up in something like `demo.png`, our regex passes and then image is not loaded in the home page, so we need to have array of 10 perfect working images preferably of webP fromat as it loads faster, and when `generate random` button is clicked one of the 10 images url form the array should get auto filled.

### Current Behavior

We can have invalid images like demo.png when creating a post

### Proposed Enhancement

Add a button `generate random image url` in the textbox of image url which autofills with the perfect image from array of image urls 

### Use Case

It helps in enhancing UI of the app, so we don't see broken images in the app

### Blockers

_No response_

### Additional Information/ Attachments

_No response_

### PR DESCRIPTION
**Pull request by jjinendra3**
## Summary
Updated image modal to allow users to select any of the 7 images from the webp format instead of randomizing.

## Description
In this pull request, I've modified the image modal functionality to enhance user experience. Now, users can specifically choose from any of the 7 available images in the webp format instead of the previous randomization. This change was implemented to give users more control over the visuals they want to interact with. I have also fixed the code according to the feedback received in the previous PR.

## Images
https://drive.google.com/drive/folders/14JFGZFLu-vtUvZdi7CmX4zrihCY0Lv21

Please find the new video in the drive (Updated from the last PR)

## Issue(s) Addressed
Closes #49 

## Prerequisites
- [x] Have followed all the [CONTRIBUTING GUIDELINES](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md#guidelines-for-contributions)

### CODE REVIEW

File: frontend/src/pages/add-blog.tsx [hunk 1]
```diff
@@ -6,6 +6,15 @@ import 'react-toastify/dist/ReactToastify.css';
...
+const imageUrls = [
+  'https://i.ibb.co/3z72vmc/clean-lake-mountains-range-trees-nature-4k.webp',
+  'https://i.ibb.co/y8vQnDc/c4fedab1-4041-4db5-9245-97439472cf2c.webp',
+  'https://i.ibb.co/BNjv5Nn/London-Skyline-125508655.webp',
+  'https://i.ibb.co/d0g42nr/FPO-BOR-100-800x600.webp',
+  'https://i.ibb.co/52mk2Yq/sunset-pier.webp',
+  'https://i.ibb.co/KLwfZzG/Maldives-1024x767.webp',
+  'https://i.ibb.co/qxFMj1H/sunset-horizon-clean-sky-nature.webp',
+];
 type FormData = {
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:18]: Kindly move this to constants folder

File: frontend/src/pages/add-blog.tsx [hunk 2]
```diff
@@ -58,11 +74,11 @@ function AddBlog() {
...
-    if (!imageLinkRegex.test(formData.imageLink)) {
-      toast.error('Image URL must end with .jpg, .jpeg, or .png');
-      return false;
-    }
+    // const imageLinkRegex = /\.(jpg|jpeg|png)$/i;
+    // if (!imageLinkRegex.test(formData.imageLink)) {
+    //   toast.error('Image URL must end with .jpg, .jpeg, or .png');
+    //   return false;
+    // }
     if (formData.categories.length > 3) {
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:82]: Why are we commenting this ? can we instead add WebP in this regex

File: frontend/src/pages/add-blog.tsx [hunk 3]
```diff
@@ -182,6 +211,79 @@ function AddBlog() {
           Create Blog
         </button>
       </form>
+      {modal && ( //MODAL STARTS
+        <div className="relative z-10"
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:215]: Please create a new component and use it here. Helps us in maintaining the code in long run , see which state management helps, for now you can also pass state down the prop, if you feel it very challenging to setup the state by yourself, you can pass handleImageSelect and setFormData in the Modal component and set it there, you can explore little on this part, the good practice would be context api for now if you are willing to explore, else passing the props should do :)

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Thank you @jjinendra3, Kindly address the comments

**Comment by krishnaacharyaa** [comment]
Deployment seems to fail because of the incompatible types, kindly try to fix that, let me know you need any help fixing that, happy to help :)

File: frontend/src/pages/add-blog.tsx (hunk 3 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:215]: I'm relatively new to TypeScript and haven't worked with TypeScript + React before. As a result, I couldn't complete the task when you mentioned earlier. Could we open a new refactoring issue to address this after the mege, please lmk your thoughts on this.

File: frontend/src/pages/add-blog.tsx (hunk 2 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:82]: Added :)

File: frontend/src/pages/add-blog.tsx (hunk 1 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:18]: Done :)

**Comment by jjinendra3** [comment]
> Deployment seems to fail because of the incompatible types, kindly try to fix that, let me know you need any help fixing that, happy to help :)

image

 It seems the issue was arising from the `setFormData` call, where the `selectedImage` variable had a type mismatch. Initially, the `useState` for selecting images was set to `null`, causing a compatibility issue since `selectedImage` was not strictly a string.

I've addressed this by introducing a conditional check to ensure `selectedImage` is a string before updating the state as you can see above.This modification should resolve the type incompatibility, and I believe deploying the updated code should no longer pose issues.

Regarding the reviews you requested, all have been addressed except for the modal part. Managing props in TypeScript is different from JavaScript. I suggest creating a new refactoring issue for the same.

File: frontend/src/pages/add-blog.tsx [hunk 4]
```diff
@@ -15,6 +16,13 @@ type FormData = {
   isFeaturedPost: boolean;
 };
 function AddBlog() {
+  const [selectedImage, setSelectedImage] = useState<string | null>("");
+
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:20]: Why is null required here ? "" would be by default, what is the case where the selected image is null ?

File: frontend/src/pages/add-blog.tsx [hunk 5]
```diff
@@ -57,8 +75,7 @@ function AddBlog() {
       toast.error('All fields must be filled out.');
       return false;
     }
-
-    const imageLinkRegex = /\.(jpg|jpeg|png)$/i;
+    const imageLinkRegex = /\.(jpg|jpeg|png|webp)$/i;
     if (!imageLinkRegex.test(formData.imageLink)) {
       toast.error('Image URL must end with .jpg, .jpeg, or .png');
       return false;
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:81]: Please add .webp even in the toast message

File: frontend/src/pages/add-blog.tsx [hunk 6]
```diff
@@ -122,15 +139,27 @@ function AddBlog() {
...
+              placeholder="Image URL"
+              className="w-full p-2 rounded-lg bg-gray-50 placeholder:text-gray-800 "
+              value={formData.imageLink}
+              onChange={handleInputChange}
+            />
+          </div>
+          <button
+            type="button"
+            className="bg-black text-white items-center justify-center text-base p-2 rounded-lg hover:bg-gray-800 w-full md:w-fit flex flex-2"
+            onClick={() => {
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:157]: Here can we have it's height same to the image url, don't mind I'm a little picky; because according to the UX, this button out shines more than the create blog button.

File: frontend/src/pages/add-blog.tsx [hunk 7]
```diff
@@ -42,7 +50,17 @@ function AddBlog() {
       });
     }
   };
-
+  const handleselector = () => {
+    var url = "";
+    if (typeof selectedImage === 'string') {
+      url = selectedImage;
```
Comment (krishnaacharyaa) [inline frontend/src/pages/add-blog.tsx:56]: Removing null should help us removing this overhead condition

**Review by krishnaacharyaa — CHANGES_REQUESTED** [review]
Thank you for addressing the issues, kindly address these small changes, And about the props passing I get it state may be a bit tricky, but other than js this just involves type in it, shouldn't be as tough as you tought, will create new issue anyways, no issues :)

File: frontend/src/pages/add-blog.tsx (hunk 4 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:20]: Fixed

File: frontend/src/pages/add-blog.tsx (hunk 5 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:81]: Added

File: frontend/src/pages/add-blog.tsx (hunk 6 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:157]: Fixed

File: frontend/src/pages/add-blog.tsx (hunk 7 above)
Comment (jjinendra3) [reply frontend/src/pages/add-blog.tsx:56]: Done, removed

**Comment by jjinendra3** [comment]
> Thank you for addressing the issues, kindly address these small changes, And about the props passing I get it state may be a bit tricky, but other than js this just involves type in it, shouldn't be as tough as you tought, will create new issue anyways, no issues :)

I reasearched on it and finally found the way  to do it :) So the refactoring is done, no need to create a new issue for the same

**Review by krishnaacharyaa — APPROVED** [review]
Thank you! Looks good to me ☺️
